name: "Lint and Test Charts"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lint-test:
    env:
      CHARTS_TO_TEST: "helm-templates/core-operator"
    name: "Lint and Test Helm Charts"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: "Set up Helm"
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4  # v4.3.1
        with:
          version: v3.17.0

      - name: "Set up Python"
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@v2.8.0

      - name: "Run chart-testing (list-changed)"
        if: github.event_name == 'pull_request'
        id: list-changed
        run: |
          ct list-changed --target-branch=${{ github.event.pull_request.base.ref }} --chart-dirs=${CHARTS_TO_TEST} --charts=${CHARTS_TO_TEST}
          changed=$(ct list-changed --target-branch=${{ github.event.pull_request.base.ref }} --chart-dirs=${CHARTS_TO_TEST} --charts=${CHARTS_TO_TEST})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed=true"
          else
            echo "changed=false"
          fi

      - name: "Run chart-testing (lint) on pull_request"
        if: github.event_name == 'pull_request' && steps.list-changed.outputs.changed == 'true'
        run: ct lint --chart-dirs=${CHARTS_TO_TEST} --charts=${CHARTS_TO_TEST} --debug --validate-maintainers=false --target-branch=${{ github.event.pull_request.base.ref }}

      - name: "Run chart-testing (lint) on workflow_dispatch"
        if: github.event_name == 'workflow_dispatch'
        run: ct lint --chart-dirs=${CHARTS_TO_TEST} --charts=${CHARTS_TO_TEST} --debug --validate-maintainers=false

      - name: "Create kind cluster"
        if: github.event_name == 'workflow_dispatch' || steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab  # v1.13.0

      - name: "Run chart-testing (install) on pull_request"
        if: github.event_name == 'pull_request' && steps.list-changed.outputs.changed == 'true'
        run: ct install --chart-dirs=${CHARTS_TO_TEST} --charts=${CHARTS_TO_TEST} --target-branch=${{ github.event.pull_request.base.ref }}

      - name: "Run chart-testing (install) on workflow_dispatch"
        if: github.event_name == 'workflow_dispatch'
        run: ct install --chart-dirs=${CHARTS_TO_TEST} --charts=${CHARTS_TO_TEST}
